### ISSUE TITLE
Реализовать пользователя (user)

### ISSUE THREAD

**Issue by Dkoplik** [Dkoplik/effective-octo-potato#21]
MVC паттерн уже плохо помню, но, подозреваю, что тут надо будет и модель сделать, и миграции, и контроллер.

Роуты для пользователя уже готовы, теперь их надо реализовать. В общем, со стороны годота по пользователям ожидаем следующий функционал:
- Возможность зарегать аккаунт. На годоте мы получаем username, email и пароль, после чего в каком-то формате это отправляем. Бекенд должен обработать эти данные и зарегать пользователя (либо отклонить регистрацию). Соответственно, на рельсе надо будет проверить сам никнейм (какие-то ограничения по длине, уникальность?, приемлемые символы), проверить почту (наверное, через письмо с подтверждением) и проверить пароль (кол-во символов, и сами символы. Хорошие и популярные требования к паролю где-нибудь загугли). Причём эти требования нам потом надо будет самим узнать, так как мы их должны будем и в годот вбить. Вот тут не уверен, но, скорее всего, сервак должен будет вернуть какой-то результат регистрации пользователя: если всё успешно, то его можно сразу залогинить, если что-то пошло не так, то об этом клиент на годоте должен узнать и высветить ошибку.
- Возможность залогиниться. Тут очень похоже на регистрацию, только теперь у нас поле username и password. Тоже валидация, тоже отправка из годота на сервак, тоже должен быть какой-то результат от сервака: либо успешно залогинились, либо что-то полшло не так (например, неправильный пароль).
- Возможность внести изменения в аккаунт. Хотя бы нужна смена пароля: пользователь вводит старый пароль, новый пароль, после чего это отправляется на сервак и тот сменяет пароль пользователя, либо возвращает отказ.
- Возможность удалить аккаунт. Залогиненый пользователь может нажать в годоте на кнопку удаления аккаунта, запрос на удаление отправляется на сервак, и тот осуществляет удаление (либо опять возвращает ошибку).

Пока что самый неявный момент: в каком формате годот должен отправлять данные на рельсу. Если для какой-то операции у рельсы уже есть чёткий формат, то нам надо будет просто в таком же формате из годота всё отправлять. Если можно что-то самому указывать, то делай, как кажется удобнее, после чего мы по этому формату и сделаем. Самое главное - нам со стороны годота надо потом знать, как и куда те или иные данные отправлять.

**Comment by Ruslan2806** [comment]
d0d382e9711c3a7ae9c6d2891a8a7685bbfd28fb
