### ISSUE TITLE
Реализовать игры (games)

### ISSUE THREAD

**Issue by Dkoplik** [Dkoplik/effective-octo-potato#22]
Опять же, вроде всё должно закончиться моделями, миграциями и контроллерами, но могу ошибаться.

По аналогии с пользователем, удобный формат отправки данных определяй на стороне рельсы, в годоте под него подстроимся. Ну и для всех входных данных должна быть валидация.

В плане игр со стороны годота ожидаем следующий функционал:

## Создание игры
Всякие лобби и подключения игроков мы обрабатываем у себя. Когда конкретная партия между двумя игроками началась, то мы отправляем запрос на сервер о создании новой партии (игры/битвы) между двумя данными игроками. В БД есть поле под завершение игры, так что надо понимать, что его в данный момент ещё не получиться заполнить. Иными словами, в БД должна появиться запись об этой игре, но ещё не все данные будут записаны.

Возможно, эта операция клиенту на годоте должна вернуть ID этой игры в БД, так как по завершению информацию в БД надо будет обновить, а других уникальных идентификаторов толком то и нет.

## Обновление (завершение) игры
Когда игра (битва) между двумя игроками закончилась, будет выявлен победитель и время окончания. Так что godot отправит запрос на изменение (дополнение) конкретной игры (битвы), где теперь появится победитель и время окончания.

## Получение информации об игре
В будуем для статистики пригодиться. Думаю, было бы неплохо, чтобы игрок в стастистике мог кликнуть по конкретной игре, и ему бы высветилась вся известная информация об этой игре. То есть, godot тогда отправляет запрос get рельсе по конкретному ID игры, и рельса должна вернуть всю информацию об этой конкретной игре. Только вместо ID игроков лучше их никнеймы возвращать.

## Удаление игры
Уже не уверен в необходимости этой опции. В общем, пока это реализовывать не стоит, ибо я не особо представляю случай, когда бы это понадобилось.
Суть в том, что неначатые игры (на стадии лобби ожидания) мы и так в БД вносить не будет, ибо в этом нет смысла. Запись об игре появиться в тот момент, как 2 игрока начали битву между друг другом, так что в БД гарантировано (в теории) будут только те игры, которые хотя бы начались.

**Comment by Ruslan2806** [comment]
4a519df7c097d9d8d8a56a508141a11f7b6dc630
